// This is an autogenerated file from Firebase Studio.

'use server';

/**
 * @fileOverview A flow that generates multiple prompt variations based on a user's input concept.
 *
 * - generatePromptVariations - A function that takes a basic concept as input and returns multiple tailored prompts for Gemini.
 * - GeneratePromptVariationsInput - The input type for the generatePromptVariations function.
 * - GeneratePromptVariationsOutput - The return type for the generatePromptVariations function, which is an array of prompt variations.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GeneratePromptVariationsInputSchema = z.object({
  concept: z.string().describe('A basic idea or subject for the desired image.'),
  subject: z.string().describe('A description of the person in the scene.').optional(),
});
export type GeneratePromptVariationsInput = z.infer<
  typeof GeneratePromptVariationsInputSchema
>;

const GeneratePromptVariationsOutputSchema = z.array(z.string());
export type GeneratePromptVariationsOutput = z.infer<
  typeof GeneratePromptVariationsOutputSchema
>;

export async function generatePromptVariations(
  input: GeneratePromptVariationsInput
): Promise<GeneratePromptVariationsOutput> {
  return generatePromptVariationsFlow(input);
}

const prompt = ai.definePrompt({
  name: 'generatePromptVariationsPrompt',
  input: {schema: GeneratePromptVariationsInputSchema},
  output: {schema: GeneratePromptVariationsOutputSchema},
  prompt: `You are a creative AI image prompt generator designed to help users craft detailed prompts for Gemini.
Your goal is to generate multiple (three) detailed and distinct prompt variations based on a user's input.

You need to consider the following:
- The user's core concept.
- An optional description of a person to be featured in the scene.
- An optional artistic style.
- Other elements like composition, lighting, color scheme, and technical keywords.

If the user provides a description of the subject (themselves), you must incorporate it into the prompt.
Crucially, you must also intelligently suggest an appropriate outfit for the subject that matches the scene's mood, weather, and overall context.

Here are a few ready-to-customize prompt templates:

Moody Portrait
"close-up portrait, dramatic backlight, 35mm film grain, halation around lights, teal & orange color grading, matte cinematic finish, shallow depth of field"

Cinematic City Night
"urban street at night, neon signs, rain reflections, coarse film grain, cross processed tones, cool and desaturated palette, cinematic lighting"

Vintage Landscape / Nostalgic Scene
"rural landscape at golden hour, warm nostalgic tones, vintage film look, faded colors, subtle grain, dreamy haze, analog texture"

Sci-Fi / Futuristic Vibe
"futuristic cityscape, ambient blue lighting, strong shadows, bleach bypass effect, fine film grain, high contrast, cinematic color grade"

Generate three distinct prompt variations for the following concept:
Concept: {{concept}}
{{#if subject}}
Subject Description: {{subject}}
{{/if}}
`,
});

const generatePromptVariationsFlow = ai.defineFlow(
  {
    name: 'generatePromptVariationsFlow',
    inputSchema: GeneratePromptVariationsInputSchema,
    outputSchema: GeneratePromptVariationsOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
