// This is an autogenerated file from Firebase Studio.

'use server';

/**
 * @fileOverview A flow that generates multiple prompt variations based on a user's input concept.
 *
 * - generatePromptVariations - A function that takes a basic concept as input and returns multiple tailored prompts for Gemini.
 * - GeneratePromptVariationsInput - The input type for the generatePromptVariations function.
 * - GeneratePromptVariationsOutput - The return type for the generatePromptVariations function, which is an array of prompt variations.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GeneratePromptVariationsInputSchema = z.object({
  concept: z.string().describe('A basic idea or subject for the desired image.'),
});
export type GeneratePromptVariationsInput = z.infer<
  typeof GeneratePromptVariationsInputSchema
>;

const GeneratePromptVariationsOutputSchema = z.array(z.string());
export type GeneratePromptVariationsOutput = z.infer<
  typeof GeneratePromptVariationsOutputSchema
>;

export async function generatePromptVariations(
  input: GeneratePromptVariationsInput
): Promise<GeneratePromptVariationsOutput> {
  return generatePromptVariationsFlow(input);
}

const prompt = ai.definePrompt({
  name: 'generatePromptVariationsPrompt',
  input: {schema: GeneratePromptVariationsInputSchema},
  output: {schema: GeneratePromptVariationsOutputSchema},
  prompt: `You are a creative AI image prompt generator designed to help users craft detailed prompts for Gemini. Generate multiple prompt variations based on the user's input concept, artistic styles, composition, lighting, color scheme, and technical keywords. Use a sleek, dark theme with deep purples, blues, and vibrant neon accents.

Here are a few ready-to-customize prompt templates:

Moody Portrait
"close-up portrait, dramatic backlight, 35mm film grain, halation around lights, teal & orange color grading, matte cinematic finish, shallow depth of field"

Cinematic City Night
"urban street at night, neon signs, rain reflections, coarse film grain, cross processed tones, cool and desaturated palette, cinematic lighting"

Vintage Landscape / Nostalgic Scene
"rural landscape at golden hour, warm nostalgic tones, vintage film look, faded colors, subtle grain, dreamy haze, analog texture"

Sci-Fi / Futuristic Vibe
"futuristic cityscape, ambient blue lighting, strong shadows, bleach bypass effect, fine film grain, high contrast, cinematic color grade"

Generate three distinct prompt variations for the following concept:

{{concept}}`,
});

const generatePromptVariationsFlow = ai.defineFlow(
  {
    name: 'generatePromptVariationsFlow',
    inputSchema: GeneratePromptVariationsInputSchema,
    outputSchema: GeneratePromptVariationsOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
